spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: Sql123.
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

fileDownloadFolder: downloadFolder
fileUploadFolder: D:\Desktop2\DeskE\Programmazione\Lezioni\5Spring\Ex28\uploadFolder
